# Generated by Django 5.2.17 on 2026-08-29 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
